# Generated by Django 4.1.3 on 2025-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rejected',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been rejected by an admin.'),
        ),
    ]
