# Generated by Django 4.1.3 on 2025-12-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if user was rejected.', null=True),
        ),
    ]
