databases:
  - name: water_billing
    databaseName: water_billing
    user: water_billing
    plan: free

services:
  - type: redis
    name: water-billing-redis
    plan: starter
    ipAllowList: []
  - type: web
    name: water-billing
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi"
    preDeployCommand: "python manage.py migrate && python manage.py seed_demo_users"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: water_billing
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: CELERY_BROKER_URL
        fromService:
          name: water-billing-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: water-billing-redis
          type: redis
          property: connectionString
  - type: worker
    name: water-billing-worker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "celery -A core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: water_billing
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: CELERY_BROKER_URL
        fromService:
          name: water-billing-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: water-billing-redis
          type: redis
          property: connectionString
