# Generated by Django 4.1.3 on 2025-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waterbill",
            name="status",
        ),
        migrations.AddField(
            model_name="waterbill",
            name="approval_status",
            field=models.TextField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending Approval",
            ),
        ),
        migrations.AddField(
            model_name="waterbill",
            name="payment_status",
            field=models.TextField(
                choices=[("Paid", "Paid"), ("Pending", "Pending")], null=True
            ),
        ),
    ]
