# Generated by Django 4.1.3 on 2025-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbill",
            name="billing_date",
            field=models.DateField(null=True),
        ),
    ]
