# Generated by Django 4.1.3 on 2025-10-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_metric_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbill",
            name="present_reading",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="waterbill",
            name="previous_reading",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="client",
            name="middle_name",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True
            ),
        ),
    ]
