# Generated by Django 4.1.3 on 2025-12-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_client_latitude_client_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="client",
            name="middle_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
