# Generated by Django 5.0.1 on 2026-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_usernotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="consump_amount",
            field=models.FloatField(default=200, null=True),
        ),
    ]
